### ISSUE TITLE
TamperMonkey Update might have broken script

### ISSUE THREAD

**Issue by Tigggger** [phw/musicbrainz-magic-tagger-button#3]
Hi,

Was thoroughly enjoying your script to keep the tag button visible (many thanks)

My version of tampermonkey just updated to v4.81.1 and it's stopped working ever since.  Occasionally the button does appear but then vanishes a couple of seconds later.  Tried the obvious like restarts and re-installs.

Just loaded ViolentMonkey and it's working fine in that.

**Comment by phw** [comment]
Thanks for the report. I also personally use Violent monkey, but I'll test with the latest version of Tampermonkey and see if I can reproduce the issue.

**Comment by phw** [comment]
Actually I experienced similar issues with ViolentMonkey. Not sure, maybe this is even related to browser changes (I'm using latest Firefox). The change in https://github.com/phw/musicbrainz-magic-tagger-button/commit/3bfc2cdb51ca534551586ebd53bd2b37d394fa83 fixes the issue for me, both with Tampermonkey and ViolentMonkey.

Could you check if this latest version works for you?

Also a general note for Tampermonkey (even though this is likely known): Tampermonkey will ask about permission to allow URL access to 127.0.0.1 (which is localhost). These are the requests to Picard and need to be allowed. See this screenshot (sorry, I only have a German screenshot right now, but I guess the general idea should be clear anyway):

![grafik](https://user-images.githubusercontent.com/29852/205243482-f3dbca2f-1fec-4f75-8893-bac23bb97841.png)

**Comment by phw** [comment]
Actually the need for the permission dialog can be avoided by adding a `@connect` declaration, so I did this as well. Latest version from https://raw.githubusercontent.com/phw/musicbrainz-magic-tagger-button/main/mb-magic-tagger-button.user.js should now work properly in Tampermonkey.

**Comment by Tigggger** [comment]
Hi,

Sorry, should have mentioned I'm using Chrome in case it's relevant.

I tried the first update you posted no change, removed the url tried again and it asks for permission which I allowed, but still no button.  It was still working fine in violentmonkey.

Just done the second update and still no change.  If viewing a release group it adds a tagger column, the buttons appear, but then they vanish after 1-2 seconds and there is nothing to click on. If viewing a release nothing appears.  It's working fine in violentmonkey still.

**Comment by phw** [comment]
Ok, thanks for the feedback. I'll check in Chrome later today. Looks like we're dealing with multiple issues :)

**Comment by phw** [comment]
@Tigggger I just checked this with latest Chrome 108 and latest Tampermonkey, no issues running the script with Tampermonkey here. 

Could you check the browser console in the developer tools (which you can open with Ctrl+Shift+I)? The user script should always output some debug messages or in your case probably some error messages. All the output but this script are prefixed with `[Magic Tagger Button]`

**Comment by Tigggger** [comment]
Well, we found the problem :-)

The script was failing on ports 8001+, when I checked my version of picard it was set to port 8000, I don't think I've ever changed that so it must be the default.

I changed picard to 8001 and it's working fine again.
